admin_controllers:
  resource: ../../src/Controller/Admin
  prefix: /admin
  name_prefix: admin_
  type: annotation

user_controllers:
  resource: ../../src/Controller/User
  prefix: /user
  name_prefix: user_
  type: annotation

userUrl_controllers:
  resource: ../../src/Controller/UserUrl
  type: annotation

default_controllers:
  resource: ../../src/Controller/Default
  type: annotation

home_controllers:
  resource: ../../src/Controller/HomePageController.php
  type: annotation

kernel:
  resource: ../../src/Kernel.php
  type: annotation
